### ISSUE TITLE
Table background vs. selection (editor's mode)

### ISSUE THREAD

**Issue by b1uegh0st** [santiyounger/Reverie-Obsidian-Theme#2]
Hi, thanks for the great theme.

I run into this problem:
- In editor mode.
- Table auto-rendered into having a green background.
- Cannot see the cursor selection inside text of the table (different color, yes, but the selection seems to be in a lower layer or something).

Can you help fixing this. For now everytime I edit table I need to switch to other theme.

Thanks,
NA

![image](https://user-images.githubusercontent.com/6695697/109951077-d2d3a800-7d0f-11eb-8986-64b2f1d78e39.png)

**Comment by santiyounger** [comment]
Hey, happy to know you are enjoying the Theme!
Thanks for bringing this to my attention, thankfully it was an easy fix. 

Just make sure to reinstall the theme by clicking on "Use" and it should work

![image](https://user-images.githubusercontent.com/51902730/110825965-97cafa80-8262-11eb-81b8-73425829388f.png)


Let me know if it's working alright for you, or if you need anything else!

Have a great day!
